# Generated by Django 5.0.2 on 2024-02-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Call_contact', models.CharField(max_length=100)),
                ('Relation', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Subject', models.CharField(max_length=100)),
                ('Reminder', models.CharField(max_length=100)),
                ('Purpose', models.CharField(max_length=100)),
                ('Agenda', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=100)),
                ('Middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Last_name', models.CharField(max_length=100)),
                ('Company', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Status', models.CharField(choices=[('Active', 'active'), ('Inactive', 'inactive')], max_length=20)),
                ('Mobile', models.CharField(max_length=12)),
                ('WhatsApp_line', models.CharField(max_length=12)),
                ('location', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Customer_source', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Deal_name', models.CharField(max_length=100)),
                ('Contact_name', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
                ('Deal_source', models.CharField(max_length=100)),
                ('Amount', models.CharField(max_length=100)),
                ('Closing_date', models.DateField()),
                ('Expected_revenue', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Active', 'active'), ('Inactive', 'inactive')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('price', models.CharField(max_length=200)),
                ('Category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Invoice_number', models.CharField(max_length=100)),
                ('Customer_name', models.CharField(max_length=100)),
                ('Item', models.CharField(max_length=100)),
                ('Invoice_date', models.DateField()),
                ('Payment_due', models.DateField()),
                ('Valid_until', models.DateField()),
                ('Amount', models.CharField(max_length=100)),
                ('Total_amount', models.CharField(max_length=100)),
                ('Balance_payment', models.CharField(max_length=100)),
                ('Status', models.CharField(choices=[('Unpaid', 'paid'), ('Paid', 'paid'), ('Overdue', 'overdue')], max_length=20)),
                ('Note', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=100)),
                ('Title', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Company', models.CharField(max_length=100)),
                ('Industry', models.CharField(max_length=100)),
                ('Lead_source', models.CharField(max_length=100)),
                ('Rating', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Service_Type', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Assigned_To', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('Start_time', models.TimeField()),
                ('End_time', models.TimeField()),
                ('Agenda', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Active', 'active'), ('Inactive', 'inactive')], max_length=10)),
                ('duration', models.DurationField()),
                ('base_price', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=100)),
                ('Task_date', models.DateField()),
                ('Assigned_to', models.CharField(max_length=100)),
                ('starting_time', models.TimeField(max_length=100)),
                ('Ending_time', models.TimeField(max_length=100)),
                ('Total_duration', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('Priority', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=200)),
            ],
        ),
    ]
